const fs = require('fs');
const file = 'c:/Dev/NexSys/src/features/bridge/BridgePage.tsx';
let c = fs.readFileSync(file, 'utf8');

c = c.replace(/~2 minuten \(on-chain bevestiging\)/g, '~2 minutes (on-chain confirmation)');
c = c.replace(/Dit is een eenrichtingstransactie\. SYS wordt vernietigd op de UTXO-laag en aangemaakt op NEVM\. Controleer het NEVM-adres — dit is onomkeerbaar\./g, 'This is a one-way transaction. SYS is burned on the UTXO layer and minted on NEVM. Check the NEVM address carefully — this is irreversible.');
c = c.replace(/Tweestaps proces: \(1\) SYS wordt gebrand op UTXO en geclaimd op NEVM via SPV-bewijs\. \(2\) Geclaimde SYS wordt automatisch gestort op Rollux L2\. Controleer het Rollux-adres zorgvuldig\./g, 'Two-step process: (1) SYS is burned on UTXO and claimed on NEVM via SPV proof. (2) Claimed SYS is automatically deposited to Rollux L2. Check the Rollux address carefully.');
c = c.replace(/SYS → SYSX conversie wordt bevestigd\.\.\./g, 'Confirming SYS → SYSX conversion...');
c = c.replace(/Burn wordt bevestigd\.\.\./g, 'Confirming burn...');
c = c.replace(/Wallet vergrendeld — ontgrendel wallet om de bridge te hervatten\./g, 'Wallet locked — unlock wallet to resume bridging.');
c = c.replace(/Wallet vergrendeld — ontgrendel wallet om de burn te hervatten\./g, 'Wallet locked — unlock wallet to resume burn.');
c = c.replace(/statusMessage: "Hervatten\.\.\."/g, 'statusMessage: "Resuming..."');
c = c.replace(/Hervat auto-burn voor/g, 'Resume auto-burn for');
c = c.replace(/Ontgrendel uw Syscoin UTXO Node Wallet om door te gaan met bridgen\./g, 'Unlock your Syscoin UTXO Node Wallet to continue bridging.');
c = c.replace(/Hervat Actie/g, 'Resume Action');
c = c.replace(/Bridge wordt uitgevoerd\.\.\./g, 'Bridge in progress...');
c = c.replace(/Ontgrendel EVM Wallet \(NEVM\/Rollux\)/g, 'Unlock EVM Wallet (NEVM/Rollux)');
c = c.replace(/Stap 1: EVM-referenties decrypten\.\.\./g, 'Step 1: Decrypting EVM credentials...');
c = c.replace(/Stap 2: SPV-bewijs ophalen van de node\.\.\./g, 'Step 2: Fetching SPV proof from node...');
c = c.replace(/Stap 3: SPV-proof verzenden naar NEVM \(relayTx\)\.\.\./g, 'Step 3: Broadcasting SPV proof to NEVM (relayTx)...');
c = c.replace(/Stap 4: Wachten op NEVM-bevestiging\.\.\./g, 'Step 4: Waiting for NEVM confirmation...');
c = c.replace(/Stap 5: Storten op Rollux L2 \(depositETHTo\)\.\.\./g, 'Step 5: Depositing to Rollux L2 (depositETHTo)...');
c = c.replace(/Stap 6: Wachten op Rollux L2-bevestiging\.\.\./g, 'Step 6: Waiting for Rollux L2 confirmation...');
c = c.replace(/Voer uw <strong>EVM Master Wachtwoord<\/strong> in om uw opgeslagen EVM-referenties te decrypten en de claim-transactie op de NEVM\/Rollux chain te ondertekenen\./g, 'Enter your <strong>EVM Master Password</strong> to decrypt your saved EVM credentials and sign the claim transaction on the NEVM/Rollux chain.');
c = c.replace(/💡 Let op: Dit is het in-app wachtwoord dat u hebt ingesteld in de Settings, <em>niet<\/em> het Syscoin UTXO Node Wachtwoord\./g, '💡 Note: This is the in-app password you set in Settings, <em>not</em> the Syscoin UTXO Node Passphrase.');
c = c.replace(/placeholder="EVM Master Wachtwoord"/g, 'placeholder="EVM Master Password"');
c = c.replace(/Bezig met claimen\.\.\./g, 'Claiming...');
c = c.replace(/Signeer & Claim/g, 'Sign & Claim');
c = c.replace(/cancelLabel="Annuleren"/g, 'cancelLabel="Cancel"');
c = c.replace(/>Annuleren</g, '>Cancel<');
c = c.replace(/Ontgrendel Syscoin Core Node Wallet \(UTXO\)/g, 'Unlock Syscoin Core Node Wallet (UTXO)');
c = c.replace(/Voer uw <strong>Syscoin UTXO Node Wachtwoord<\/strong> in om uw lokale Syscoin Core portemonnee te ontgrendelen voor de burn-transactie\./g, 'Enter your <strong>Syscoin UTXO Node Passphrase</strong> to unlock your local Syscoin Core wallet for the burn transaction.');
c = c.replace(/Automatische actie na ontgrendelen:/g, 'Automatic action after unlock:');
c = c.replace(/⚠️ Let op: Dit is de passphrase van uw lokale Syscoin Core node wallet, <em>niet<\/em> het EVM Master Wachtwoord\./g, '⚠️ Note: This is the passphrase of your local Syscoin Core node wallet, <em>not</em> the EVM Master Password.');
c = c.replace(/Syscoin UTXO Node Wachtwoord \(Passphrase\)/g, 'Syscoin UTXO Node Passphrase');
c = c.replace(/Geldigheidsduur \(seconden\)/g, 'Validity (seconds)');
c = c.replace(/Ontgrendeling mislukt/g, 'Unlock Failed');
c = c.replace(/Ontgrendelen…/g, 'Unlocking…');
c = c.replace(/Ontgrendel Wallet/g, 'Unlock Wallet');
c = c.replace(/Passphrase van de Syscoin Core Node/g, 'Passphrase of the Syscoin Core Node');

fs.writeFileSync(file, c);
console.log('Translations applied successfully.');
